#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import zipfile

from .log import DataLog
from .motec import MotecLog
from .output import atomic_write_motec_pair, ensure_output_targets
from .parsers import auto_detect_log_type
from .rcz_archive import discover_rcz_sessions

DESCRIPTION = """Generates MoTeC .ld files from external log files generated by: CAN bus dumps, CSV
 files, COBB Accessport CSV files, or RaceChrono CSV files"""

EPILOG = """The CAN bus log must be the same format as what is generated by 'candump' with the '-l'
option from the linux package can-utils. A MoTeC channel will be created for every signal in the
DBC file that has messages in the CAN log. The signal name and units will be directly copied from
the DBC file.

CSV files must have time as their first column. A MoTeC channel will be generated for all remaining
columns. All channels will not have any units assigned.

COBB Accessport CSV logs are simply generated by starting a logging session on the accessport. A
MoTeC channel will be created for every channel logged, the name and units will be directly copied
over.

RaceChrono CSV files are parsed looking for the 'Time (s)' header row and mapped to standard MoTeC
channel names and units automatically where applicable.
"""


def get_rcz_stints(rcz_path, target_session=None):
    stints = set()
    with zipfile.ZipFile(rcz_path, 'r') as z:
        namelist = z.namelist()
        session_prefix = "sessions/%s/" % target_session if target_session else ""
        session_key = session_prefix + "session.json"
        if session_key in namelist:
            session_json = json.loads(z.read(session_key).decode("utf-8"))
            for lap in session_json.get("laps", []):
                stints.add(lap.get("sessionResume", 0))
        for name in namelist:
            if name.startswith(session_prefix + "resume_"):
                parts = name[len(session_prefix):].split("/")
                if parts[0].startswith("resume_"):
                    try:
                        st_id = int(parts[0].replace("resume_", ""))
                        stints.add(st_id)
                    except ValueError:
                        pass
    if not stints:
        stints.add(0)
    return sorted(list(stints))


_get_stints = get_rcz_stints


def normalize_venue_name(name):
    from .metadata import normalize_venue
    return normalize_venue(name)


_normalize_venue = normalize_venue_name


def parse_gear_ratio_thresholds(value):
    try:
        thresholds = tuple(float(part.strip()) for part in value.split(","))
    except ValueError as exc:
        raise argparse.ArgumentTypeError("gear ratio thresholds must be comma-separated numbers") from exc
    if len(thresholds) != 6 or any(a <= b for a, b in zip(thresholds, thresholds[1:])):
        raise argparse.ArgumentTypeError(
            "gear ratio thresholds must contain six strictly descending values"
        )
    return thresholds


def _output_paths(args, out_base):
    if out_base:
        ld_filename = os.path.splitext(out_base)[0] + ".ld"
    else:
        input_dir, input_filename = os.path.split(args.log)
        input_stem = os.path.splitext(input_filename)[0]
        ld_filename = os.path.join(input_dir, input_stem + ".ld")
    ldx_filename = os.path.splitext(ld_filename)[0] + ".ldx"
    targets = [ld_filename, ldx_filename]
    if getattr(args, "gpx", False):
        targets.append(os.path.splitext(ld_filename)[0] + ".gpx")
    if getattr(args, "kml", False):
        targets.append(os.path.splitext(ld_filename)[0] + ".kml")
    if getattr(args, "csv", False):
        targets.append(_csv_output_path(ld_filename, args.log))
    return ld_filename, ldx_filename, targets


def _csv_output_path(ld_filename, source_path):
    csv_filename = os.path.splitext(ld_filename)[0] + ".csv"
    if os.path.normcase(os.path.abspath(csv_filename)) == os.path.normcase(
        os.path.abspath(source_path)
    ):
        csv_filename = os.path.splitext(ld_filename)[0] + "_export.csv"
    return csv_filename


_auto_detect_log_type = auto_detect_log_type


def process_one_file(args, stint_override=None, output_override=None,
                     session_override=None):
    stint_arg = stint_override if stint_override is not None else args.stint
    out_base = output_override if output_override is not None else args.output
    target_session = (
        session_override
        if session_override is not None
        else getattr(args, "session", None)
    )
    if str(target_session).lower() == "all":
        target_session = None

    active_type = args.log_type
    if active_type == "AUTO" or args.log.lower().endswith(".rcz"):
        if args.log.lower().endswith(".rcz"):
            active_type = "RCZ"
        else:
            active_type = auto_detect_log_type(args.log)
            print(f"Auto-detected log type: {active_type}")

    if active_type == "RCZ" and str(stint_arg).lower() == "all":
        try:
            stints = get_rcz_stints(args.log, target_session=target_session)
        except Exception as e:
            print(f"Warning: Failed checking stints, falling back to default export: {e}")
        else:
            if len(stints) > 1:
                print(f"Auto-detected {len(stints)} stints in RCZ log: {stints}")
                base_output = out_base if out_base else args.log
                base_name, _ = os.path.splitext(base_output)
                exported_files = []
                for st in stints:
                    st_out = f"{base_name}_stint{st}"
                    print(f"\n=== Exporting Stint {st} -> {st_out} ===")
                    process_one_file(
                        args,
                        stint_override=str(st),
                        output_override=st_out,
                        session_override=target_session,
                    )
                    exported_files.append(st_out)
                print("Auto-stint split export complete.")
                return exported_files

    ld_filename, ldx_filename, output_targets = _output_paths(args, out_base)
    ensure_output_targets(
        output_targets,
        force=getattr(args, "force", False),
        source_path=args.log,
    )

    print("Loading log...")
    data_log = DataLog()

    if active_type == "CAN":
        try:
            import cantools
        except ImportError:
            print("ERROR: 'cantools' package is required for CAN log processing.")
            print("  Install with: pip install cantools")
            sys.exit(1)

        with open(args.log, "r") as file:
            lines = file.readlines()

        if not os.path.isfile(args.dbc):
            print("ERROR: DBC file %s does not exist" % args.dbc)
            sys.exit(1)

        print("Loading DBC...")
        can_db = cantools.database.load_file(args.dbc)

        print("Extracting data...")
        data_log.from_can_log(lines, can_db)
    elif active_type == "CSV":
        with open(args.log, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_csv_log(lines)
    elif active_type == "ACCESSPORT":
        with open(args.log, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_accessport_log(lines)
    elif active_type == "RACECHRONO":
        with open(args.log, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
        print("Extracting data...")
        data_log.from_racechrono_log(lines, target_lap=args.lap)
    elif active_type == "PBBUDDY":
        with open(args.log, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
        print("Extracting PB Buddy data...")
        data_log.from_pbbuddy_log(lines, target_lap=args.lap)
    elif active_type == "VBO":
        with open(args.log, "r", encoding="utf-8", errors="ignore") as file:
            lines = file.readlines()
        print("Extracting Racelogic VBO data...")
        data_log.from_vbo_log(lines, target_lap=args.lap)
    elif active_type == "RCZ":
        print("Extracting RCZ data directly...")
        data_log.from_rcz_log(args.log, target_lap=args.lap,
                              target_stint=stint_arg, min_lap_sec=args.min_lap_sec,
                              mask_interp_gaps=args.mask_interp_gaps,
                              target_session=target_session)
    elif active_type == "IBT":
        print("Extracting iRacing .ibt telemetry...")
        data_log.from_ibt_log(args.log)
    elif active_type == "XRK":
        print("Extracting AIM XRK/XRZ telemetry...")
        data_log.from_xrk_log(args.log, target_lap=args.lap)
    elif active_type == "FIT":
        print("Extracting Garmin .fit telemetry...")
        data_log.from_fit_log(args.log, target_lap=args.lap)

    if not data_log.channels:
        print("ERROR: Failed to find any channels in log data")
        sys.exit(1)

    print("Parsed %.1fs log with %s channels:" % (data_log.duration(), len(data_log.channels)))
    for channel_name, channel in data_log.channels.items():
        print("\t%s" % channel)

    resample_freq = data_log.resample(args.frequency, mask_interp_gaps=args.mask_interp_gaps)
    print("Resampled channels at %.1f Hz..." % resample_freq)

    print("Calculating math channels (g-source: %s)..." % getattr(args, "g_source", "auto"))
    data_log.calculate_math_channels(
        g_source=getattr(args, "g_source", "auto"),
        gear_ratio_thresholds=getattr(args, "gear_ratio_thresholds", None),
    )

    print("Converting to MoTeC log...")

    meta = getattr(data_log, "metadata", {})

    venue_name = args.venue_name if args.venue_name else meta.get("venue_name", "")
    if not venue_name and hasattr(data_log, "rcz_metadata") and data_log.rcz_metadata.get("trackName"):
        venue_name = data_log.rcz_metadata.get("trackName")

    if not venue_name:
        filename = os.path.basename(args.log)
        venue_name = _normalize_venue(filename)
        if venue_name == filename:
            venue_name = _normalize_venue(meta.get("event_session", meta.get("Session", "")))
    else:
        venue_name = _normalize_venue(venue_name)

    data_log.metadata["venue_name"] = venue_name

    event_name = args.event_name if args.event_name else meta.get("event_name", "")
    if not event_name and venue_name:
        event_name = venue_name.replace("_", " ").title() + " Track Day" if not venue_name.endswith("Track Day") else venue_name

    driver_name = args.driver if args.driver else meta.get("driver", meta.get("Racer", ""))
    if not driver_name:
        driver_name = "Unknown Driver"

    vehicle_name = args.vehicle_id if args.vehicle_id else meta.get(
        "vehicle_id", meta.get("Vehicle", "")
    )

    motec_log = MotecLog()
    if getattr(data_log, "datetime", None):
        motec_log.datetime = data_log.datetime
    motec_log.driver = driver_name
    motec_log.vehicle_id = vehicle_name
    motec_log.vehicle_weight = args.vehicle_weight
    motec_log.vehicle_type = args.vehicle_type
    motec_log.vehicle_comment = args.vehicle_comment
    motec_log.venue_name = venue_name
    motec_log.event_name = event_name
    motec_log.event_session = args.event_session if args.event_session else meta.get("event_session", "")
    motec_log.long_comment = args.long_comment if args.long_comment else meta.get("long_comment", meta.get("Comment", ""))
    motec_log.short_comment = args.short_comment if args.short_comment else meta.get("short_comment", "")

    motec_log.initialize()
    motec_log.add_all_channels(data_log)

    print("Saving MoTeC log...")
    output_dir = os.path.dirname(ld_filename)
    if output_dir and not os.path.isdir(output_dir):
        print("Directory '%s' does not exist, will create it" % output_dir)
        os.makedirs(output_dir)

    ensure_output_targets(
        output_targets,
        force=getattr(args, "force", False),
        source_path=args.log,
    )
    try:
        atomic_write_motec_pair(motec_log, data_log, ld_filename, ldx_filename)
        print("Saved .ld file: %s" % ld_filename)
        print("Saved .ldx file: %s" % ldx_filename)
    except PermissionError:
        raise PermissionError(
            "output is locked; close the file in MoTeC i2 and retry: %s" % ld_filename
        )

    if args.gpx:
        gpx_filename = os.path.splitext(ld_filename)[0] + ".gpx"
        if motec_log.write_gpx(gpx_filename, data_log):
            print("Saved .gpx track file: %s" % gpx_filename)

    if args.kml:
        kml_filename = os.path.splitext(ld_filename)[0] + ".kml"
        if motec_log.write_kml(kml_filename, data_log):
            print("Saved .kml Google Earth file: %s" % kml_filename)

    if args.csv:
        csv_filename = _csv_output_path(ld_filename, args.log)
        if motec_log.write_csv(csv_filename, data_log, wallclock=getattr(args, "csv_wallclock", False)):
            print("Saved .csv data file: %s" % csv_filename)

    print("Done!")
    return output_targets


_process_one = process_one_file


def build_parser():
    parser = argparse.ArgumentParser(description=DESCRIPTION, epilog=EPILOG)
    parser.add_argument("log", type=str, help="Path to logfile")
    parser.add_argument("log_type", type=str, help="Type of log to process",
                        choices=["CAN", "CSV", "ACCESSPORT", "RACECHRONO", "RCZ", "PBBUDDY", "VBO", "IBT", "XRK", "FIT", "AUTO"])

    parser.add_argument("--output", type=str,
                        help="Name of output file, defaults to the same filename as 'log'")
    parser.add_argument("--output-dir", type=str,
                        help="Output directory for '--session all'")
    parser.add_argument("--list-sessions", action="store_true",
                        help="List sessions in a RaceChrono backup without exporting")
    parser.add_argument("--session", type=str,
                        help="RaceChrono backup session ID, or 'all'")
    parser.add_argument("--force", action="store_true",
                        help="Replace existing output files after verified temporary writes")
    parser.add_argument("--g-source", type=str, default="auto", choices=["auto", "sensor", "calc"],
                        help="Source for G-force channels: 'auto' (use IMU sensor if present, fallback to GPS calc), 'sensor' (only IMU sensor), or 'calc' (force derive from GPS)")
    parser.add_argument("--gear-ratio-thresholds", type=parse_gear_ratio_thresholds, default=None,
                        help="Six descending RPM/km/h thresholds for derived gears 1-6 (default: 110,70,52,42,33,20)")
    parser.add_argument("--frequency", type=str, default="auto",
                        help="Fixed frequency to resample all channels at (e.g. 20, 25, 50, 100 or 'auto', default: auto)")
    parser.add_argument("--gpx", action="store_true", help="Also generate GPX track file")
    parser.add_argument("--kml", action="store_true", help="Also generate KML Google Earth track file")
    parser.add_argument("--csv", action="store_true", help="Also generate CSV data file (RaceStudio / Excel import)")
    parser.add_argument("--csv-wallclock", action="store_true", default=False, dest="csv_wallclock",
                        help="Write wall-clock timestamps in CSV instead of elapsed seconds")
    parser.add_argument("--dbc", type=str, help="Path to DBC file, required if log type CAN")

    parser.add_argument("--lap", type=str, default="all",
                        help="Reconstructed lap number within the selected stint, or 'all' (default: all)")
    parser.add_argument("--stint", type=str, default="all",
                        help="RCZ sessionResume stint to export")
    parser.add_argument("--min-lap-sec", "--min_lap_sec", type=float, default=15.0,
                        dest="min_lap_sec",
                        help="Minimum reconstructed out/timed/in segment duration in seconds (default: 15.0)")
    parser.add_argument("--mask-interp-gaps", "--mask_interp_gaps", action="store_true", default=False, dest="mask_interp_gaps",
                        help="Mask sample interpolation gaps (>1s) with NaN instead of interpolating through them (default: False)")
    parser.add_argument("--driver", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_id", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_weight", type=int, default=0, help="Motec log metadata field")
    parser.add_argument("--vehicle_type", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--vehicle_comment", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--venue_name", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--event_name", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--event_session", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--long_comment", type=str, default="", help="Motec log metadata field")
    parser.add_argument("--short_comment", type=str, default="", help="Motec log metadata field")
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)

    if str(args.frequency).lower() != "auto":
        try:
            if float(args.frequency) <= 0:
                print("ERROR: --frequency must be positive or 'auto'")
                sys.exit(1)
        except ValueError:
            print("ERROR: Invalid --frequency value '%s'. Must be a number or 'auto'" % args.frequency)
            sys.exit(1)

    if not math.isfinite(args.min_lap_sec) or args.min_lap_sec <= 0:
        print("ERROR: --min-lap-sec must be a positive finite number")
        sys.exit(1)

    if args.log:
        args.log = os.path.expanduser(args.log)
    if args.dbc:
        args.dbc = os.path.expanduser(args.dbc)
    if args.output:
        args.output = os.path.expanduser(args.output)
    if args.output_dir:
        args.output_dir = os.path.expanduser(args.output_dir)
    if args.log.lower().endswith(".rcz") and args.log_type != "RCZ":
        print("WARNING: Overriding --log_type '%s' to 'RCZ' because input file has .rcz extension" % args.log_type)
        args.log_type = "RCZ"

    if args.log.lower().endswith((".xrk", ".xrz")) and args.log_type != "XRK":
        print("WARNING: Overriding --log_type '%s' to 'XRK' because input file has .xrk/.xrz extension" % args.log_type)
        args.log_type = "XRK"

    if args.log.lower().endswith(".fit") and args.log_type != "FIT":
        print("WARNING: Overriding --log_type '%s' to 'FIT' because input file has .fit extension" % args.log_type)
        args.log_type = "FIT"

    if os.path.isdir(args.log):
        dir_path = args.log
        ext_filter = ".rcz" if args.log_type == "RCZ" else ".xrk" if args.log_type == "XRK" else ".fit" if args.log_type == "FIT" else ".csv"
        matching_files = sorted([
            os.path.join(dir_path, f) for f in os.listdir(dir_path)
            if f.lower().endswith(ext_filter)
        ])
        if not matching_files:
            print("ERROR: No %s files found in directory '%s'" % (ext_filter, dir_path))
            return 1

        print("Found %d %s files in '%s'..." % (len(matching_files), ext_filter, dir_path))
        for fpath in matching_files:
            print("\n" + "=" * 80)
            print("Processing: %s" % fpath)
            args.log = fpath
            args.output = None
            if args.log_type == "RCZ" and str(args.stint).lower() == "all":
                try:
                    stints = _get_stints(fpath)
                except Exception as e:
                    print("ERROR: Failed to read RCZ stints in %s: %s" % (fpath, e))
                    continue
                if len(stints) > 1:
                    base_name, _ = os.path.splitext(fpath)
                    for st in stints:
                        st_out = f"{base_name}_stint{st}"
                        print("\n=== Exporting Stint %s -> %s ===" % (st, st_out))
                        _process_one(args, stint_override=str(st), output_override=st_out)
                    continue
            _process_one(args)
        print("\nBatch directory processing complete.")
        return 0

    if not os.path.isfile(args.log):
        print("ERROR: log file %s does not exist" % args.log)
        return 1

    if args.log_type == "RCZ":
        try:
            backup_sessions = discover_rcz_sessions(args.log)
        except (OSError, ValueError, zipfile.BadZipFile) as exc:
            print("ERROR: Failed to inspect RCZ archive: %s" % exc)
            return 1
        if args.list_sessions:
            if not backup_sessions:
                print("This RCZ contains one root session; --list-sessions is for backup archives.")
                return 0
            print("Found %d sessions:" % len(backup_sessions))
            print("Session ID\tTrack\tDuration\tLaps\tStints")
            for session in backup_sessions:
                print(
                    "%s\t%s\t%.1fs\t%d\t%s"
                    % (
                        session.session_id,
                        session.track_name,
                        session.duration_sec,
                        session.lap_count,
                        ",".join(str(value) for value in session.stints),
                    )
                )
            return 0
        if backup_sessions:
            if not args.session:
                print(
                    "ERROR: RaceChrono backup contains %d sessions; use "
                    "--list-sessions, --session ID, or --session all."
                    % len(backup_sessions)
                )
                return 1
            if str(args.session).lower() != "all":
                selected = next(
                    (
                        item for item in backup_sessions
                        if item.session_id == args.session
                    ),
                    None,
                )
                if selected is None:
                    print("ERROR: Unknown RCZ session ID '%s'." % args.session)
                    print("Use --list-sessions to see valid IDs.")
                    return 1
                if args.output_dir:
                    print("ERROR: --output-dir is only valid with --session all")
                    return 1
                output_base = args.output
                if not output_base:
                    backup_stem = os.path.splitext(args.log)[0]
                    output_base = "%s_%s" % (backup_stem, selected.session_id)
                try:
                    _process_one(
                        args,
                        output_override=output_base,
                        session_override=selected.session_id,
                    )
                except (OSError, RuntimeError, ValueError) as exc:
                    print("ERROR: %s" % exc)
                    return 1
                return 0
            if args.output:
                print("ERROR: --output cannot be used with --session all; use --output-dir")
                return 1
            if str(args.stint).lower() != "all":
                print("ERROR: --session all requires --stint all")
                return 1

            output_dir = args.output_dir
            if not output_dir:
                output_dir = os.path.splitext(args.log)[0] + "_sessions"
            jobs = []
            all_targets = []
            for session in backup_sessions:
                for stint in session.stints:
                    stem = session.session_id
                    if len(session.stints) > 1:
                        stem += "_stint%s" % stint
                    output_base = os.path.join(output_dir, stem)
                    _, _, targets = _output_paths(args, output_base)
                    jobs.append((session.session_id, stint, output_base))
                    all_targets.extend(targets)
            try:
                ensure_output_targets(
                    all_targets,
                    force=args.force,
                    source_path=args.log,
                )
            except (OSError, ValueError) as exc:
                print("ERROR: %s" % exc)
                print("Preflight failed; no sessions were exported.")
                return 1

            succeeded = 0
            failures = []
            for session_id, stint, output_base in jobs:
                print("\n=== Exporting %s stint %s ===" % (session_id, stint))
                try:
                    _process_one(
                        args,
                        stint_override=str(stint),
                        output_override=output_base,
                        session_override=session_id,
                    )
                    succeeded += 1
                except SystemExit as exc:
                    failures.append((session_id, stint, "exit code %s" % exc.code))
                except Exception as exc:
                    failures.append((session_id, stint, str(exc)))
                if failures and failures[-1][0:2] == (session_id, stint):
                    print("ERROR: %s stint %s failed: %s" % failures[-1])

            print(
                "\nRCZ backup export complete: %d succeeded, %d failed."
                % (succeeded, len(failures))
            )
            return 1 if failures else 0
        elif args.session:
            print("ERROR: --session is only valid for a multi-session RCZ backup")
            return 1

    if args.log_type == "CAN" and not os.path.isfile(args.dbc):
        print("ERROR: DBC file %s does not exist" % args.dbc)
        return 1

    if args.log_type == "RCZ" and str(args.stint).lower() == "all":
        try:
            stints = _get_stints(args.log)
        except Exception as e:
            print("ERROR: Failed to read RCZ stints: %s" % e)
            return 1

        if len(stints) > 1:
            print("Auto-detected %d stints in RCZ log: %s" % (len(stints), stints))
            base_output = args.output if args.output else args.log
            base_name, ext = os.path.splitext(base_output)
            for st in stints:
                st_out = f"{base_name}_stint{st}"
                print("\n=== Exporting Stint %s -> %s ===" % (st, st_out))
                _process_one(args, stint_override=str(st), output_override=st_out)
            print("Auto-stint split export complete.")
            return 0

    try:
        _process_one(args)
    except (OSError, RuntimeError, ValueError) as exc:
        print("ERROR: %s" % exc)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
